spring:
  datasource:
    username: root
    password: dqk.0204
    url: jdbc:mysql://localhost:3306/credit_system?serverTime=UTC&zoneUseUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
